spring.application.name=deploy

# Ini yang diubah biar nyambung ke container database sebelah
spring.datasource.url=jdbc:postgresql://db-postgres:5432/praktikum_db
spring.datasource.username=praktikum_user
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect